---
title: "HW3: Mixed Supervised + Unsupervised Tasks on the Zymo Mock Dataset"
format:
  html:
    toc: true
    toc-title: Contents
    toc-depth: 4
    code-fold: show
    self-contained: true
    html-math-method: mathml
jupyter: python3
---

## Introduction

The [ZymoBIOMICS mock microbial community](https://github.com/LomanLab/mockcommunity) is a standardized mixture of known bacterial and fungal taxa at defined proportions. Because the true composition is known, it is widely used as a benchmarking and proof-of-concept dataset for evaluating bioinformatics pipelines, feature representations, and ecological analysis methods.

In this homework, you will use the Zymo mock community as a controlled testbed to assess the quality of **GenSLMs sequence embeddings**.



### Background

GenSLMs embeddings are pretrained representations derived from the **GenSLM foundation model** (GitHub: https://github.com/ramanathanlab/genslm).  
They are intended to capture biologically meaningful patterns such as evolutionary or phylogenetic relatedness and shared functional motifs.

There are 10 reference genomes in this dataset. Metagenomic reads have been assembled into contigs. The reference genome IDs correspond to:

- **0**: *Bacillus subtilis*
- **1**: *Cryptococcus neoformans*
- **2**: *Enterococcus faecalis*
- **3**: *Escherichia coli*
- **4**: *Lactobacillus fermentum*
- **5**: *Listeria monocytogenes*
- **6**: *Pseudomonas aeruginosa*
- **7**: *Saccharomyces cerevisiae*
- **8**: *Salmonella enterica*
- **9**: *Staphylococcus aureus*

Among these genomes, **E. coli** and **Salmonella** share ~87.04% similarity, and **Bacillus** and **Staphylococcus** share ~72.25% similarity.



### Hypothesis

We hypothesize that GenSLMs embeddings encode evolutionary and functional signals strongly enough that:

1. A classifier trained on the embeddings can accurately predict contig origin (genome ID).
2. Low-dimensional projections (PCA / UMAP / t-SNE) reveal coherent clusters aligned with genome IDs, including known similarity pairs (e.g., *E. coli* vs. *Salmonella*).
3. Clustering algorithms applied to the embeddings approximate true contig origin groupings with high homogeneity and completeness.



### Strategy

1. Load contig-level embeddings and genome IDs.
2. Perform a stratified train/test split to evaluate generalization.
3. Train multiple multi-class classifiers (Logistic Regression, LightGBM, XGBoost, CatBoost) and select the best model based on macro F1.
4. To speed up classification, reduce the dimensionality using PCA and UMAP, and evaluate how different numbers of components affect classification performance.
5. Visualize the embeddings using PCA, t-SNE, and UMAP with tuned hyperparameters; annotate notable overlaps (e.g., *E. coli* vs. *Salmonella*).
6. Apply clustering (DBSCAN / HDBSCAN / KMeans) on the 2D reduced space and compute homogeneity and completeness scores.




### Evaluation

- **Classification**: macro precision, macro recall, macro F1, accuracy.
- **Visualization**: qualitative cluster separation and overlapping
- **Clustering**: homogeneity_score, completeness_score, number of clusters vs expected genomes, outlier count (if applicable).


### Open-Ended Nature

This assignment is intentionally open-ended — there is no single “correct” setting.  
You are encouraged to explore reasonable hyperparameters.  
For some steps, I also provide my own settings so that everyone starts from the same baseline.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
genslm_npz = np.load("zymo_genslm_embeddings.npz")
genslm_npz['e'].shape
genslm_npz['id'].shape

(11724,)

In [5]:
genslm_embed = pd.DataFrame(genslm_npz['e'])
genslm_embed['rid'] = genslm_npz['id']
genslm_embed=genslm_embed.sample(frac=1)
genslm_embed.describe()

,0,1,2,3,4,5,6,7,8,9,...,3831,3832,3833,3834,3835,3836,3837,3838,3839,rid
count,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,...,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000,11724.000000
mean,-0.172946,0.229652,-0.091656,0.312128,0.221963,-0.049410,0.394963,-0.066101,0.109899,0.072875,...,0.035922,0.245670,0.310494,-0.097445,-0.038705,-0.068324,-0.027750,-0.171403,-1.567976,2.696691
std,0.107995,0.070311,0.091085,0.130252,0.260921,0.037091,0.111554,0.044227,0.169603,0.072104,...,0.045836,0.076481,0.064397,0.149072,0.061731,0.055843,0.054115,0.165558,0.234706,2.662503
min,-0.414492,-0.170474,-0.428855,-0.189030,-0.202179,-0.231486,-0.068627,-0.311310,-0.246488,-0.289764,...,-0.243446,-0.108656,-0.095644,-0.376422,-0.333230,-0.330913,-0.217874,-0.518213,-1.966708,0.000000
25%,-0.281451,0.188339,-0.169851,0.190794,-0.047185,-0.071939,0.291742,-0.092717,-0.059577,0.012137,...,0.006500,0.183361,0.254403,-0.253409,-0.074627,-0.115565,-0.069625,-0.334869,-1.811119,1.000000
50%,-0.158354,0.232108,-0.103474,0.328118,0.260320,-0.047380,0.402840,-0.067295,0.129721,0.075557,...,0.037762,0.241674,0.312618,-0.076764,-0.044577,-0.072631,-0.030407,-0.139756,-1.547125,1.000000
75%,-0.075722,0.270721,-0.017998,0.433676,0.481040,-0.026329,0.496704,-0.042365,0.272931,0.133934,...,0.065301,0.317796,0.364526,0.041555,-0.002921,-0.017938,0.012859,-0.010328,-1.341360,5.000000
max,0.226545,0.548050,0.216811,0.691828,0.913784,0.229549,0.696488,0.149715,0.717532,0.328994,...,0.212165,0.430578,0.599509,0.401128,0.167531,0.099039,0.294926,0.475211,-0.598945,9.000000

In [6]:
# show the value count of the rid
genslm_embed['rid'].value_counts()

rid
1    7210
7    1326
6     694
3     519
8     496
0     405
5     297
2     284
9     282
4     211
Name: count, dtype: int64

In [7]:
# split the data into feature and target
X = genslm_embed.iloc[:, :-1].values
y = genslm_embed.iloc[:, -1].values

# split the data into training and test set with stratify
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [8]:
# scale the data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Task 1: Multi-Class Classification (20 points)

Apply multiple classifiers to the dataset and identify the best-performing model based on the **macro F1 score**.  
The classifiers to evaluate include: **Multinomial Logistic Regression, LightGBM, XGBoost, and CatBoost**.

Please display the performance metrics for each classifier (e.g., **accuracy, macro precision, macro recall, macro F1**) to justify your selection of the top model for the downstream tasks.

In [9]:
# Set PyTorch as the backend for Keras before importing Keras
import os
os.environ["KERAS_BACKEND"] = "torch"

# Now import Keras (it will use PyTorch as backend)
import keras
from keras.models import Sequential
from keras.layers import Dense

# build a neural network classifier on the data
keras_classifier = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(10, activation = 'softmax')    # < softmax activation here
    ]
)

keras_classifier.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(0.001),
)

keras_classifier.fit(
    X_train, y_train,
    epochs=40
)

Epoch 1/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 1.0792
Epoch 2/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.4863
Epoch 3/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.2839
Epoch 4/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.2357
Epoch 5/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.1894
Epoch 6/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1757
Epoch 7/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1803
Epoch 8/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1491
Epoch 9/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1559
Epoch 10/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1380
Epoch 11/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.1296
Epoch 12/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1259
Epoch 13/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1154
Epoch 14/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1047
Epoch 15/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1194
Epoch 16/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1082
Epoch 17/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.1063
Epoch 18/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0956
Epoch 19/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1115
Epoch 20/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1439
Epoch 21/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0892
Epoch 22/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1071
Epoch 23/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1064
Epoch 24/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0781
Epoch 25/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0869
Epoch 26/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0686
Epoch 27/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 0.0927
Epoch 28/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0865
Epoch 29/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0741
Epoch 30/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.1207
Epoch 31/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0716
Epoch 32/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0666
Epoch 33/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0645
Epoch 34/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1000
Epoch 35/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0665
Epoch 36/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0765
Epoch 37/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0522
Epoch 38/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0964
Epoch 39/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0722
Epoch 40/40
294/294 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0704

In [10]:
# show first few predicted probability vectors from the Keras (torch-backend) model
p_nonpreferred = keras_classifier.predict(X_test)

74/74 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [11]:

y_pred = np.argmax(p_nonpreferred, axis=1)

## output the performance metrics
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

## output the precision, recall and f1 score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision Multinomial classification: {:.2f}".format(precision_score(y_test, y_pred, average='macro')))
print("Recall Multinomial classification: {:.2f}".format(recall_score(y_test, y_pred, average='macro')))
print("F1 Score Multinomial classification: {:.2f}".format(f1_score(y_test, y_pred, average='macro')))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92        81
           1       1.00      0.99      0.99      1442
           2       0.70      0.91      0.79        57
           3       0.74      0.71      0.73       104
           4       0.95      0.93      0.94        42
           5       0.86      0.80      0.83        60
           6       0.99      0.99      0.99       139
           7       0.94      0.92      0.93       265
           8       0.74      0.79      0.76        99
           9       0.88      0.89      0.88        56

    accuracy                           0.95      2345
   macro avg       0.87      0.88      0.88      2345
weighted avg       0.95      0.95      0.95      2345

Precision Multinomial classification: 0.87
Recall Multinomial classification: 0.88
F1 Score Multinomial classification: 0.88

In [12]:
#Now lets use LightGBM
import lightgbm as lgb
lgbm = lgb.LGBMClassifier(objective='multiclass',
                          num_class=10)
lgbm.fit(X_train, y_train)
y_pred_lgbm = lgbm.predict(X_test)
print("LightGBM Classification Report:")
print(classification_report(y_test, y_pred_lgbm))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.909248 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 979200
[LightGBM] [Info] Number of data points in the train set: 9379, number of used features: 3840
[LightGBM] [Info] Start training from score -3.365485
[LightGBM] [Info] Start training from score -0.486148
[LightGBM] [Info] Start training from score -3.721278
[LightGBM] [Info] Start training from score -3.117950
[LightGBM] [Info] Start training from score -4.016330
[LightGBM] [Info] Start training from score -3.678168
[LightGBM] [Info] Start training from score -2.827260
[LightGBM] [Info] Start training from score -2.179261
[LightGBM] [Info] Start training from score -3.162292
[LightGBM] [Info] Start training from score -3.725693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

LightGBM Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.88      0.93        81
           1       0.98      1.00      0.99      1442
           2       0.87      0.68      0.76        57
           3       0.71      0.68      0.70       104
           4       1.00      0.88      0.94        42
           5       0.80      0.80      0.80        60
           6       0.99      0.97      0.98       139
           7       0.89      0.95      0.92       265
           8       0.73      0.66      0.69        99
           9       0.91      0.91      0.91        56

    accuracy                           0.94      2345
   macro avg       0.89      0.84      0.86      2345
weighted avg       0.94      0.94      0.94      2345

In [13]:

#Results from LGBM

print(classification_report(y_test, y_pred_lgbm))

## output the precision, recall and f1 score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision: {:.2f}".format(precision_score(y_test, y_pred_lgbm, average='macro')))
print("Recall: {:.2f}".format(recall_score(y_test, y_pred_lgbm, average='macro')))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred_lgbm, average='macro')))

              precision    recall  f1-score   support

           0       1.00      0.88      0.93        81
           1       0.98      1.00      0.99      1442
           2       0.87      0.68      0.76        57
           3       0.71      0.68      0.70       104
           4       1.00      0.88      0.94        42
           5       0.80      0.80      0.80        60
           6       0.99      0.97      0.98       139
           7       0.89      0.95      0.92       265
           8       0.73      0.66      0.69        99
           9       0.91      0.91      0.91        56

    accuracy                           0.94      2345
   macro avg       0.89      0.84      0.86      2345
weighted avg       0.94      0.94      0.94      2345

Precision: 0.89
Recall: 0.84
F1 Score: 0.86

In [15]:
#Use xgboost
import xgboost as xgb
xgb_model = xgb.XGBClassifier(objective='multi:softmax',
                              num_class=10)


xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

In [16]:
#Results from XGBOOST

print(classification_report(y_test, y_pred_xgb))

## output the precision, recall and f1 score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision: {:.2f}".format(precision_score(y_test, y_pred_xgb, average='macro')))
print("Recall: {:.2f}".format(recall_score(y_test, y_pred_xgb, average='macro')))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred_xgb, average='macro')))

              precision    recall  f1-score   support

           0       0.99      0.88      0.93        81
           1       0.98      1.00      0.99      1442
           2       0.82      0.74      0.78        57
           3       0.76      0.71      0.74       104
           4       1.00      0.88      0.94        42
           5       0.77      0.77      0.77        60
           6       0.99      0.96      0.97       139
           7       0.90      0.95      0.92       265
           8       0.78      0.73      0.75        99
           9       0.92      0.86      0.89        56

    accuracy                           0.94      2345
   macro avg       0.89      0.85      0.87      2345
weighted avg       0.94      0.94      0.94      2345

Precision: 0.89
Recall: 0.85
F1 Score: 0.87

In [18]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.2)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [20]:
#Catboost for multiclass classification

from catboost import CatBoostClassifier
catboost_model = CatBoostClassifier(loss_function='MultiClass',
                                    task_type = "GPU")
catboost_model.fit(X_train, y_train, verbose = True)
y_pred_catboost = catboost_model.predict(X_test)

Learning rate set to 0.102472
0:	learn: 1.6991639	total: 296ms	remaining: 4m 55s
1:	learn: 1.4354643	total: 469ms	remaining: 3m 54s
2:	learn: 1.2561588	total: 636ms	remaining: 3m 31s
3:	learn: 1.1198878	total: 804ms	remaining: 3m 20s
4:	learn: 1.0108836	total: 970ms	remaining: 3m 12s
5:	learn: 0.9221921	total: 1.13s	remaining: 3m 7s
6:	learn: 0.8506827	total: 1.31s	remaining: 3m 5s
7:	learn: 0.7907017	total: 1.47s	remaining: 3m 2s
8:	learn: 0.7368114	total: 1.64s	remaining: 3m 1s
9:	learn: 0.6918476	total: 1.82s	remaining: 2m 59s
10:	learn: 0.6522343	total: 1.99s	remaining: 2m 58s
11:	learn: 0.6169180	total: 2.16s	remaining: 2m 58s
12:	learn: 0.5856078	total: 2.34s	remaining: 2m 57s
13:	learn: 0.5556048	total: 2.52s	remaining: 2m 57s
14:	learn: 0.5302127	total: 2.7s	remaining: 2m 57s
15:	learn: 0.5072179	total: 2.87s	remaining: 2m 56s
16:	learn: 0.4851333	total: 3.04s	remaining: 2m 56s
17:	learn: 0.4651458	total: 3.21s	remaining: 2m 55s
18:	learn: 0.4463506	total: 3.38s	remaining: 2m 54s
19:	learn: 0.4300753	total: 3.56s	remaining: 2m 54s
20:	learn: 0.4151180	total: 3.73s	remaining: 2m 53s
21:	learn: 0.4007793	total: 3.89s	remaining: 2m 53s
22:	learn: 0.3879648	total: 4.07s	remaining: 2m 53s
23:	learn: 0.3760348	total: 4.25s	remaining: 2m 52s
24:	learn: 0.3656466	total: 4.43s	remaining: 2m 52s
25:	learn: 0.3557182	total: 4.6s	remaining: 2m 52s
26:	learn: 0.3462464	total: 4.77s	remaining: 2m 51s
27:	learn: 0.3381920	total: 4.92s	remaining: 2m 50s
28:	learn: 0.3300100	total: 5.09s	remaining: 2m 50s
29:	learn: 0.3232868	total: 5.25s	remaining: 2m 49s
30:	learn: 0.3170061	total: 5.42s	remaining: 2m 49s
31:	learn: 0.3112389	total: 5.57s	remaining: 2m 48s
32:	learn: 0.3055953	total: 5.74s	remaining: 2m 48s
33:	learn: 0.3000560	total: 5.89s	remaining: 2m 47s
34:	learn: 0.2961726	total: 6.03s	remaining: 2m 46s
35:	learn: 0.2911872	total: 6.2s	remaining: 2m 45s
36:	learn: 0.2870478	total: 6.35s	remaining: 2m 45s
37:	learn: 0.2828916	total: 6.51s	remaining: 2m 44s
38:	learn: 0.2783100	total: 6.68s	remaining: 2m 44s
39:	learn: 0.2747503	total: 6.82s	remaining: 2m 43s
40:	learn: 0.2713531	total: 6.97s	remaining: 2m 42s
41:	learn: 0.2694742	total: 7.12s	remaining: 2m 42s
42:	learn: 0.2655122	total: 7.3s	remaining: 2m 42s
43:	learn: 0.2616393	total: 7.46s	remaining: 2m 42s
44:	learn: 0.2591082	total: 7.63s	remaining: 2m 41s
45:	learn: 0.2558346	total: 7.8s	remaining: 2m 41s
46:	learn: 0.2543592	total: 7.95s	remaining: 2m 41s
47:	learn: 0.2517437	total: 8.09s	remaining: 2m 40s
48:	learn: 0.2500627	total: 8.25s	remaining: 2m 40s
49:	learn: 0.2485990	total: 8.38s	remaining: 2m 39s
50:	learn: 0.2453383	total: 8.53s	remaining: 2m 38s
51:	learn: 0.2429266	total: 8.69s	remaining: 2m 38s
52:	learn: 0.2398407	total: 8.85s	remaining: 2m 38s
53:	learn: 0.2383354	total: 8.99s	remaining: 2m 37s
54:	learn: 0.2344845	total: 9.16s	remaining: 2m 37s
55:	learn: 0.2324745	total: 9.34s	remaining: 2m 37s
56:	learn: 0.2299242	total: 9.49s	remaining: 2m 36s
57:	learn: 0.2275091	total: 9.65s	remaining: 2m 36s
58:	learn: 0.2253298	total: 9.8s	remaining: 2m 36s
59:	learn: 0.2236867	total: 10s	remaining: 2m 36s
60:	learn: 0.2222829	total: 10.2s	remaining: 2m 37s
61:	learn: 0.2209132	total: 10.4s	remaining: 2m 36s
62:	learn: 0.2196739	total: 10.5s	remaining: 2m 36s
63:	learn: 0.2180016	total: 10.7s	remaining: 2m 36s
64:	learn: 0.2159725	total: 10.9s	remaining: 2m 37s
65:	learn: 0.2138716	total: 11.1s	remaining: 2m 37s
66:	learn: 0.2121626	total: 11.3s	remaining: 2m 37s
67:	learn: 0.2100094	total: 11.5s	remaining: 2m 37s
68:	learn: 0.2089494	total: 11.7s	remaining: 2m 37s
69:	learn: 0.2072131	total: 11.8s	remaining: 2m 36s
70:	learn: 0.2052355	total: 12s	remaining: 2m 36s
71:	learn: 0.2036325	total: 12.2s	remaining: 2m 36s
72:	learn: 0.2022723	total: 12.3s	remaining: 2m 36s
73:	learn: 0.2018583	total: 12.5s	remaining: 2m 36s
74:	learn: 0.2008698	total: 12.6s	remaining: 2m 35s
75:	learn: 0.1992204	total: 12.8s	remaining: 2m 35s
76:	learn: 0.1972542	total: 13s	remaining: 2m 36s
77:	learn: 0.1952489	total: 13.2s	remaining: 2m 36s
78:	learn: 0.1942264	total: 13.4s	remaining: 2m 36s
79:	learn: 0.1934575	total: 13.6s	remaining: 2m 36s
80:	learn: 0.1924983	total: 13.8s	remaining: 2m 36s
81:	learn: 0.1910169	total: 13.9s	remaining: 2m 36s
82:	learn: 0.1904061	total: 14.1s	remaining: 2m 35s
83:	learn: 0.1885702	total: 14.3s	remaining: 2m 35s
84:	learn: 0.1876420	total: 14.4s	remaining: 2m 35s
85:	learn: 0.1863911	total: 14.6s	remaining: 2m 35s
86:	learn: 0.1851478	total: 14.8s	remaining: 2m 35s
87:	learn: 0.1837825	total: 14.9s	remaining: 2m 34s
88:	learn: 0.1825059	total: 15.1s	remaining: 2m 34s
89:	learn: 0.1810565	total: 15.3s	remaining: 2m 34s
90:	learn: 0.1796400	total: 15.4s	remaining: 2m 34s
91:	learn: 0.1787115	total: 15.6s	remaining: 2m 33s
92:	learn: 0.1774574	total: 15.7s	remaining: 2m 33s
93:	learn: 0.1764307	total: 15.9s	remaining: 2m 33s
94:	learn: 0.1749557	total: 16s	remaining: 2m 32s
95:	learn: 0.1740669	total: 16.2s	remaining: 2m 32s
96:	learn: 0.1731195	total: 16.3s	remaining: 2m 32s
97:	learn: 0.1715959	total: 16.5s	remaining: 2m 31s
98:	learn: 0.1706549	total: 16.6s	remaining: 2m 31s
99:	learn: 0.1693517	total: 16.8s	remaining: 2m 31s
100:	learn: 0.1682527	total: 17s	remaining: 2m 30s
101:	learn: 0.1673076	total: 17.1s	remaining: 2m 30s
102:	learn: 0.1666563	total: 17.2s	remaining: 2m 30s
103:	learn: 0.1654555	total: 17.4s	remaining: 2m 30s
104:	learn: 0.1641940	total: 17.6s	remaining: 2m 29s
105:	learn: 0.1632438	total: 17.7s	remaining: 2m 29s
106:	learn: 0.1625578	total: 17.9s	remaining: 2m 29s
107:	learn: 0.1613298	total: 18s	remaining: 2m 29s
108:	learn: 0.1599823	total: 18.2s	remaining: 2m 28s
109:	learn: 0.1591452	total: 18.4s	remaining: 2m 28s
110:	learn: 0.1584666	total: 18.5s	remaining: 2m 28s
111:	learn: 0.1580695	total: 18.7s	remaining: 2m 28s
112:	learn: 0.1576272	total: 18.8s	remaining: 2m 27s
113:	learn: 0.1570201	total: 19s	remaining: 2m 27s
114:	learn: 0.1562427	total: 19.1s	remaining: 2m 27s
115:	learn: 0.1550868	total: 19.3s	remaining: 2m 27s
116:	learn: 0.1541439	total: 19.5s	remaining: 2m 26s
117:	learn: 0.1535338	total: 19.6s	remaining: 2m 26s
118:	learn: 0.1526228	total: 19.8s	remaining: 2m 26s
119:	learn: 0.1522807	total: 19.9s	remaining: 2m 26s
120:	learn: 0.1516557	total: 20.1s	remaining: 2m 25s
121:	learn: 0.1509508	total: 20.2s	remaining: 2m 25s
122:	learn: 0.1505399	total: 20.4s	remaining: 2m 25s
123:	learn: 0.1501923	total: 20.5s	remaining: 2m 24s
124:	learn: 0.1495481	total: 20.7s	remaining: 2m 24s
125:	learn: 0.1488058	total: 20.8s	remaining: 2m 24s
126:	learn: 0.1484582	total: 21s	remaining: 2m 24s
127:	learn: 0.1479417	total: 21.1s	remaining: 2m 24s
128:	learn: 0.1473366	total: 21.3s	remaining: 2m 23s
129:	learn: 0.1461680	total: 21.4s	remaining: 2m 23s
130:	learn: 0.1452981	total: 21.6s	remaining: 2m 23s
131:	learn: 0.1448279	total: 21.7s	remaining: 2m 22s
132:	learn: 0.1442403	total: 21.9s	remaining: 2m 22s
133:	learn: 0.1437784	total: 22.1s	remaining: 2m 22s
134:	learn: 0.1430007	total: 22.3s	remaining: 2m 22s
135:	learn: 0.1425783	total: 22.5s	remaining: 2m 22s
136:	learn: 0.1418203	total: 22.6s	remaining: 2m 22s
137:	learn: 0.1410564	total: 22.8s	remaining: 2m 22s
138:	learn: 0.1405524	total: 23s	remaining: 2m 22s
139:	learn: 0.1395181	total: 23.2s	remaining: 2m 22s
140:	learn: 0.1391935	total: 23.4s	remaining: 2m 22s
141:	learn: 0.1385338	total: 23.6s	remaining: 2m 22s
142:	learn: 0.1378108	total: 23.7s	remaining: 2m 22s
143:	learn: 0.1373159	total: 23.9s	remaining: 2m 22s
144:	learn: 0.1366985	total: 24.1s	remaining: 2m 21s
145:	learn: 0.1362202	total: 24.2s	remaining: 2m 21s
146:	learn: 0.1353500	total: 24.4s	remaining: 2m 21s
147:	learn: 0.1348008	total: 24.5s	remaining: 2m 21s
148:	learn: 0.1342911	total: 24.7s	remaining: 2m 21s
149:	learn: 0.1337473	total: 24.8s	remaining: 2m 20s
150:	learn: 0.1329559	total: 25s	remaining: 2m 20s
151:	learn: 0.1323659	total: 25.1s	remaining: 2m 20s
152:	learn: 0.1320889	total: 25.3s	remaining: 2m 19s
153:	learn: 0.1315335	total: 25.4s	remaining: 2m 19s
154:	learn: 0.1311088	total: 25.6s	remaining: 2m 19s
155:	learn: 0.1304123	total: 25.7s	remaining: 2m 19s
156:	learn: 0.1298254	total: 25.9s	remaining: 2m 18s
157:	learn: 0.1292244	total: 26s	remaining: 2m 18s
158:	learn: 0.1288235	total: 26.2s	remaining: 2m 18s
159:	learn: 0.1284877	total: 26.3s	remaining: 2m 18s
160:	learn: 0.1279487	total: 26.4s	remaining: 2m 17s
161:	learn: 0.1272291	total: 26.6s	remaining: 2m 17s
162:	learn: 0.1267425	total: 26.8s	remaining: 2m 17s
163:	learn: 0.1261615	total: 26.9s	remaining: 2m 17s
164:	learn: 0.1257983	total: 27.1s	remaining: 2m 16s
165:	learn: 0.1254577	total: 27.2s	remaining: 2m 16s
166:	learn: 0.1250634	total: 27.3s	remaining: 2m 16s
167:	learn: 0.1246106	total: 27.5s	remaining: 2m 16s
168:	learn: 0.1239698	total: 27.6s	remaining: 2m 15s
169:	learn: 0.1233784	total: 27.8s	remaining: 2m 15s
170:	learn: 0.1229994	total: 27.9s	remaining: 2m 15s
171:	learn: 0.1225469	total: 28.1s	remaining: 2m 15s
172:	learn: 0.1221855	total: 28.3s	remaining: 2m 15s
173:	learn: 0.1216031	total: 28.4s	remaining: 2m 14s
174:	learn: 0.1212817	total: 28.6s	remaining: 2m 14s
175:	learn: 0.1206624	total: 28.7s	remaining: 2m 14s
176:	learn: 0.1201954	total: 28.9s	remaining: 2m 14s
177:	learn: 0.1196645	total: 29s	remaining: 2m 13s
178:	learn: 0.1193099	total: 29.2s	remaining: 2m 13s
179:	learn: 0.1188480	total: 29.3s	remaining: 2m 13s
180:	learn: 0.1185863	total: 29.5s	remaining: 2m 13s
181:	learn: 0.1179676	total: 29.6s	remaining: 2m 13s
182:	learn: 0.1175310	total: 29.8s	remaining: 2m 12s
183:	learn: 0.1171129	total: 29.9s	remaining: 2m 12s
184:	learn: 0.1167479	total: 30.1s	remaining: 2m 12s
185:	learn: 0.1163398	total: 30.2s	remaining: 2m 12s
186:	learn: 0.1159997	total: 30.4s	remaining: 2m 12s
187:	learn: 0.1153328	total: 30.5s	remaining: 2m 11s
188:	learn: 0.1149123	total: 30.7s	remaining: 2m 11s
189:	learn: 0.1147020	total: 30.8s	remaining: 2m 11s
190:	learn: 0.1144622	total: 30.9s	remaining: 2m 11s
191:	learn: 0.1140193	total: 31.1s	remaining: 2m 10s
192:	learn: 0.1135156	total: 31.2s	remaining: 2m 10s
193:	learn: 0.1132947	total: 31.4s	remaining: 2m 10s
194:	learn: 0.1127171	total: 31.6s	remaining: 2m 10s
195:	learn: 0.1122228	total: 31.7s	remaining: 2m 10s
196:	learn: 0.1118811	total: 31.9s	remaining: 2m 9s
197:	learn: 0.1114997	total: 32s	remaining: 2m 9s
198:	learn: 0.1107989	total: 32.2s	remaining: 2m 9s
199:	learn: 0.1104533	total: 32.4s	remaining: 2m 9s
200:	learn: 0.1098504	total: 32.5s	remaining: 2m 9s
201:	learn: 0.1093859	total: 32.7s	remaining: 2m 9s
202:	learn: 0.1089429	total: 32.8s	remaining: 2m 8s
203:	learn: 0.1087291	total: 33s	remaining: 2m 8s
204:	learn: 0.1083202	total: 33.1s	remaining: 2m 8s
205:	learn: 0.1081086	total: 33.3s	remaining: 2m 8s
206:	learn: 0.1076777	total: 33.4s	remaining: 2m 7s
207:	learn: 0.1073397	total: 33.5s	remaining: 2m 7s
208:	learn: 0.1070238	total: 33.7s	remaining: 2m 7s
209:	learn: 0.1067400	total: 33.8s	remaining: 2m 7s
210:	learn: 0.1062979	total: 34s	remaining: 2m 7s
211:	learn: 0.1058373	total: 34.1s	remaining: 2m 6s
212:	learn: 0.1050444	total: 34.3s	remaining: 2m 6s
213:	learn: 0.1047442	total: 34.5s	remaining: 2m 6s
214:	learn: 0.1044209	total: 34.6s	remaining: 2m 6s
215:	learn: 0.1041469	total: 34.8s	remaining: 2m 6s
216:	learn: 0.1038220	total: 35s	remaining: 2m 6s
217:	learn: 0.1035323	total: 35.2s	remaining: 2m 6s
218:	learn: 0.1031479	total: 35.4s	remaining: 2m 6s
219:	learn: 0.1026778	total: 35.6s	remaining: 2m 6s
220:	learn: 0.1023340	total: 35.8s	remaining: 2m 6s
221:	learn: 0.1020459	total: 35.9s	remaining: 2m 5s
222:	learn: 0.1017558	total: 36.1s	remaining: 2m 5s
223:	learn: 0.1013962	total: 36.3s	remaining: 2m 5s
224:	learn: 0.1010418	total: 36.4s	remaining: 2m 5s
225:	learn: 0.1008764	total: 36.6s	remaining: 2m 5s
226:	learn: 0.1006358	total: 36.7s	remaining: 2m 5s
227:	learn: 0.1003507	total: 36.9s	remaining: 2m 4s
228:	learn: 0.1001255	total: 37s	remaining: 2m 4s
229:	learn: 0.0998394	total: 37.2s	remaining: 2m 4s
230:	learn: 0.0995831	total: 37.3s	remaining: 2m 4s
231:	learn: 0.0992620	total: 37.5s	remaining: 2m 4s
232:	learn: 0.0989254	total: 37.6s	remaining: 2m 3s
233:	learn: 0.0985737	total: 37.8s	remaining: 2m 3s
234:	learn: 0.0981100	total: 38s	remaining: 2m 3s
235:	learn: 0.0979230	total: 38.1s	remaining: 2m 3s
236:	learn: 0.0975458	total: 38.3s	remaining: 2m 3s
237:	learn: 0.0972506	total: 38.4s	remaining: 2m 2s
238:	learn: 0.0970146	total: 38.5s	remaining: 2m 2s
239:	learn: 0.0969004	total: 38.7s	remaining: 2m 2s
240:	learn: 0.0964965	total: 38.9s	remaining: 2m 2s
241:	learn: 0.0963308	total: 39s	remaining: 2m 2s
242:	learn: 0.0959234	total: 39.2s	remaining: 2m 2s
243:	learn: 0.0956729	total: 39.3s	remaining: 2m 1s
244:	learn: 0.0954501	total: 39.5s	remaining: 2m 1s
245:	learn: 0.0950986	total: 39.6s	remaining: 2m 1s
246:	learn: 0.0948136	total: 39.8s	remaining: 2m 1s
247:	learn: 0.0943855	total: 39.9s	remaining: 2m 1s
248:	learn: 0.0941662	total: 40.1s	remaining: 2m
249:	learn: 0.0939474	total: 40.3s	remaining: 2m
250:	learn: 0.0935430	total: 40.4s	remaining: 2m
251:	learn: 0.0932919	total: 40.6s	remaining: 2m
252:	learn: 0.0929131	total: 40.7s	remaining: 2m
253:	learn: 0.0926942	total: 40.9s	remaining: 2m
254:	learn: 0.0922910	total: 41s	remaining: 1m 59s
255:	learn: 0.0920975	total: 41.2s	remaining: 1m 59s
256:	learn: 0.0918824	total: 41.3s	remaining: 1m 59s
257:	learn: 0.0916479	total: 41.5s	remaining: 1m 59s
258:	learn: 0.0912897	total: 41.6s	remaining: 1m 59s
259:	learn: 0.0909562	total: 41.8s	remaining: 1m 58s
260:	learn: 0.0905909	total: 42s	remaining: 1m 58s
261:	learn: 0.0904297	total: 42.1s	remaining: 1m 58s
262:	learn: 0.0901298	total: 42.3s	remaining: 1m 58s
263:	learn: 0.0899589	total: 42.4s	remaining: 1m 58s
264:	learn: 0.0898102	total: 42.6s	remaining: 1m 58s
265:	learn: 0.0895886	total: 42.7s	remaining: 1m 57s
266:	learn: 0.0889299	total: 42.9s	remaining: 1m 57s
267:	learn: 0.0885226	total: 43s	remaining: 1m 57s
268:	learn: 0.0882683	total: 43.2s	remaining: 1m 57s
269:	learn: 0.0879211	total: 43.4s	remaining: 1m 57s
270:	learn: 0.0874245	total: 43.5s	remaining: 1m 57s
271:	learn: 0.0871661	total: 43.7s	remaining: 1m 56s
272:	learn: 0.0869208	total: 43.8s	remaining: 1m 56s
273:	learn: 0.0864204	total: 44s	remaining: 1m 56s
274:	learn: 0.0861265	total: 44.1s	remaining: 1m 56s
275:	learn: 0.0859566	total: 44.3s	remaining: 1m 56s
276:	learn: 0.0857397	total: 44.4s	remaining: 1m 55s
277:	learn: 0.0855700	total: 44.6s	remaining: 1m 55s
278:	learn: 0.0852340	total: 44.7s	remaining: 1m 55s
279:	learn: 0.0850224	total: 44.8s	remaining: 1m 55s
280:	learn: 0.0849348	total: 45s	remaining: 1m 55s
281:	learn: 0.0845342	total: 45.2s	remaining: 1m 54s
282:	learn: 0.0842312	total: 45.3s	remaining: 1m 54s
283:	learn: 0.0839070	total: 45.4s	remaining: 1m 54s
284:	learn: 0.0836666	total: 45.6s	remaining: 1m 54s
285:	learn: 0.0833560	total: 45.7s	remaining: 1m 54s
286:	learn: 0.0831667	total: 45.9s	remaining: 1m 53s
287:	learn: 0.0828364	total: 46s	remaining: 1m 53s
288:	learn: 0.0826690	total: 46.2s	remaining: 1m 53s
289:	learn: 0.0824055	total: 46.4s	remaining: 1m 53s
290:	learn: 0.0822007	total: 46.5s	remaining: 1m 53s
291:	learn: 0.0818271	total: 46.7s	remaining: 1m 53s
292:	learn: 0.0816149	total: 46.9s	remaining: 1m 53s
293:	learn: 0.0812750	total: 47.2s	remaining: 1m 53s
294:	learn: 0.0809740	total: 47.3s	remaining: 1m 53s
295:	learn: 0.0807720	total: 47.5s	remaining: 1m 53s
296:	learn: 0.0804496	total: 47.7s	remaining: 1m 52s
297:	learn: 0.0801223	total: 47.9s	remaining: 1m 52s
298:	learn: 0.0800300	total: 48s	remaining: 1m 52s
299:	learn: 0.0799302	total: 48.1s	remaining: 1m 52s
300:	learn: 0.0797238	total: 48.3s	remaining: 1m 52s
301:	learn: 0.0793853	total: 48.5s	remaining: 1m 52s
302:	learn: 0.0791927	total: 48.6s	remaining: 1m 51s
303:	learn: 0.0790696	total: 48.8s	remaining: 1m 51s
304:	learn: 0.0788507	total: 49s	remaining: 1m 51s
305:	learn: 0.0786090	total: 49.1s	remaining: 1m 51s
306:	learn: 0.0783768	total: 49.3s	remaining: 1m 51s
307:	learn: 0.0781880	total: 49.4s	remaining: 1m 50s
308:	learn: 0.0779444	total: 49.6s	remaining: 1m 50s
309:	learn: 0.0778252	total: 49.7s	remaining: 1m 50s
310:	learn: 0.0775040	total: 49.8s	remaining: 1m 50s
311:	learn: 0.0772784	total: 50s	remaining: 1m 50s
312:	learn: 0.0771068	total: 50.1s	remaining: 1m 50s
313:	learn: 0.0767749	total: 50.3s	remaining: 1m 49s
314:	learn: 0.0765972	total: 50.4s	remaining: 1m 49s
315:	learn: 0.0764187	total: 50.6s	remaining: 1m 49s
316:	learn: 0.0761759	total: 50.7s	remaining: 1m 49s
317:	learn: 0.0760080	total: 50.9s	remaining: 1m 49s
318:	learn: 0.0758430	total: 51s	remaining: 1m 48s
319:	learn: 0.0755736	total: 51.2s	remaining: 1m 48s
320:	learn: 0.0753895	total: 51.3s	remaining: 1m 48s
321:	learn: 0.0751703	total: 51.5s	remaining: 1m 48s
322:	learn: 0.0748176	total: 51.6s	remaining: 1m 48s
323:	learn: 0.0745184	total: 51.8s	remaining: 1m 48s
324:	learn: 0.0743670	total: 52s	remaining: 1m 47s
325:	learn: 0.0742053	total: 52.1s	remaining: 1m 47s
326:	learn: 0.0740932	total: 52.2s	remaining: 1m 47s
327:	learn: 0.0739125	total: 52.4s	remaining: 1m 47s
328:	learn: 0.0736789	total: 52.5s	remaining: 1m 47s
329:	learn: 0.0735101	total: 52.7s	remaining: 1m 46s
330:	learn: 0.0733560	total: 52.9s	remaining: 1m 46s
331:	learn: 0.0732125	total: 53s	remaining: 1m 46s
332:	learn: 0.0729778	total: 53.2s	remaining: 1m 46s
333:	learn: 0.0728319	total: 53.3s	remaining: 1m 46s
334:	learn: 0.0727723	total: 53.4s	remaining: 1m 46s
335:	learn: 0.0726584	total: 53.6s	remaining: 1m 45s
336:	learn: 0.0723322	total: 53.8s	remaining: 1m 45s
337:	learn: 0.0720858	total: 53.9s	remaining: 1m 45s
338:	learn: 0.0717597	total: 54.1s	remaining: 1m 45s
339:	learn: 0.0715897	total: 54.3s	remaining: 1m 45s
340:	learn: 0.0714405	total: 54.4s	remaining: 1m 45s
341:	learn: 0.0712211	total: 54.6s	remaining: 1m 44s
342:	learn: 0.0711033	total: 54.7s	remaining: 1m 44s
343:	learn: 0.0709091	total: 54.8s	remaining: 1m 44s
344:	learn: 0.0707155	total: 55s	remaining: 1m 44s
345:	learn: 0.0705586	total: 55.1s	remaining: 1m 44s
346:	learn: 0.0703640	total: 55.3s	remaining: 1m 44s
347:	learn: 0.0702034	total: 55.4s	remaining: 1m 43s
348:	learn: 0.0700286	total: 55.6s	remaining: 1m 43s
349:	learn: 0.0698684	total: 55.7s	remaining: 1m 43s
350:	learn: 0.0697137	total: 55.9s	remaining: 1m 43s
351:	learn: 0.0695335	total: 56s	remaining: 1m 43s
352:	learn: 0.0694257	total: 56.2s	remaining: 1m 42s
353:	learn: 0.0692107	total: 56.3s	remaining: 1m 42s
354:	learn: 0.0689840	total: 56.5s	remaining: 1m 42s
355:	learn: 0.0687815	total: 56.6s	remaining: 1m 42s
356:	learn: 0.0684881	total: 56.8s	remaining: 1m 42s
357:	learn: 0.0683639	total: 57s	remaining: 1m 42s
358:	learn: 0.0682334	total: 57.1s	remaining: 1m 41s
359:	learn: 0.0680060	total: 57.3s	remaining: 1m 41s
360:	learn: 0.0678400	total: 57.4s	remaining: 1m 41s
361:	learn: 0.0675572	total: 57.6s	remaining: 1m 41s
362:	learn: 0.0673714	total: 57.7s	remaining: 1m 41s
363:	learn: 0.0672212	total: 57.9s	remaining: 1m 41s
364:	learn: 0.0669765	total: 58s	remaining: 1m 40s
365:	learn: 0.0666118	total: 58.2s	remaining: 1m 40s
366:	learn: 0.0665217	total: 58.3s	remaining: 1m 40s
367:	learn: 0.0663292	total: 58.5s	remaining: 1m 40s
368:	learn: 0.0661760	total: 58.7s	remaining: 1m 40s
369:	learn: 0.0660551	total: 58.9s	remaining: 1m 40s
370:	learn: 0.0657633	total: 59.1s	remaining: 1m 40s
371:	learn: 0.0655996	total: 59.2s	remaining: 1m 40s
372:	learn: 0.0654525	total: 59.4s	remaining: 1m 39s
373:	learn: 0.0652365	total: 59.6s	remaining: 1m 39s
374:	learn: 0.0651058	total: 59.8s	remaining: 1m 39s
375:	learn: 0.0649364	total: 60s	remaining: 1m 39s
376:	learn: 0.0648514	total: 1m	remaining: 1m 39s
377:	learn: 0.0646670	total: 1m	remaining: 1m 39s
378:	learn: 0.0645361	total: 1m	remaining: 1m 39s
379:	learn: 0.0643612	total: 1m	remaining: 1m 38s
380:	learn: 0.0641314	total: 1m	remaining: 1m 38s
381:	learn: 0.0640148	total: 1m	remaining: 1m 38s

In [21]:
#Results from CatBoost

print(classification_report(y_test, y_pred_catboost))

## output the precision, recall and f1 score
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision: {:.2f}".format(precision_score(y_test, y_pred_catboost, average='macro')))
print("Recall: {:.2f}".format(recall_score(y_test, y_pred_catboost, average='macro')))
print("F1 Score: {:.2f}".format(f1_score(y_test, y_pred_catboost, average='macro')))

              precision    recall  f1-score   support

           0       0.96      0.91      0.94        81
           1       0.98      1.00      0.99      1442
           2       0.84      0.74      0.79        57
           3       0.78      0.73      0.75       104
           4       1.00      0.93      0.96        42
           5       0.83      0.80      0.81        60
           6       1.00      0.98      0.99       139
           7       0.91      0.96      0.93       265
           8       0.81      0.74      0.77        99
           9       0.94      0.91      0.93        56

    accuracy                           0.95      2345
   macro avg       0.91      0.87      0.89      2345
weighted avg       0.95      0.95      0.95      2345

Precision: 0.91
Recall: 0.87
F1 Score: 0.89

Looking at the performance of all models we can conclude that the CatBoost model perfomed the best. It had the highest F1 score of 0.89, and precision score of 0.91. In addition, it had similar Recall and Accuracy to all other models.

## Task 2: Dimensionality Reduction for Efficient Classification (20 points)

Using the full embedding dimensionality for classification can be computationally intensive.  
In this step, your objective is to reduce the dimensionality of the data using **PCA** and **UMAP** to speed up classification.

Explore multiple values of `n_components` to evaluate how dimensionality affects classification performance.  
Use the **best-performing classifier identified in Task 1**.

The dimensionalities to explore are:

```python
n_components = [10, 20, 43, 100, 150, 200, 300, 400]
```

For each setting, report the **accuracy, macro precision, macro recall, and macro F1 score**.

After completing your experiments:

- **Identify which dimensionality reduction method (PCA or UMAP) performs better overall on this dataset.**
- **Determine the best-performing `n_components` value based on the evaluation metrics.**

**Note:** t-SNE is mainly used for reducing data to 2 or 3 dimensions for visualization.  
Because it does not scale effectively to higher-dimensional embeddings, we **exclude it** from this task.

## Task 3: Visualizing High-Dimensional Embeddings Using PCA, t-SNE, and UMAP (20 points)

Visualize the high-dimensional data using **PCA**, **t-SNE**, and **UMAP**.  
Keep in mind that tuning the hyperparameters for t-SNE and UMAP is essential for producing informative plots.

Experiment with different settings to generate the most insightful visualizations, and **explicitly report the best hyperparameters you identified through your experiments** in your submission.

## Task 4: Evaluating Clustering Algorithms on 2D Embeddings (30 points)

Clustering algorithms often struggle with the curse of dimensionality, which can lead to poor performance on high-dimensional data.  
To address this, use the **2-dimensional representation** obtained from **t-SNE** in Task 2 (`n_components = 2`, `perplexity = 25`).

Apply **three different clustering algorithms** to the 2D data and evaluate their effectiveness.  
For each algorithm, report the following:

- **Visualization** of the clustering result (dimension = 2)
- **Number of clusters**
- **Number of outliers** (`cluster_labels == -1`, if applicable)
- **Completeness score** and **Homogeneity score**  
  (refer to scikit-learn documentation for how to compute these metrics given ground-truth labels)

**Note:**  
Since clustering is unsupervised, use the entire dataset when tuning hyperparameters (no train-test split needed).

## Task 5: Summary of Best Results and Reflection (10 points)

Summarize the best results you obtained from each of the previous tasks and explain what you learned from this assignment.

# Task
Train a LightGBM Classifier model on `X_train` and `y_train`, predict on `X_test`, and then compute and print the accuracy, macro precision, macro recall, and macro F1 score of the predictions.

## Implement LightGBM Classifier

### Subtask:
Train a LightGBM classifier model on the training data, make predictions on the test data, and then evaluate its performance using accuracy, macro precision, macro recall, and macro F1 score.

**Reasoning**:
Implement the LightGBM classifier as requested, including importing necessary libraries, initializing and training the model, making predictions, and evaluating its performance using accuracy, macro precision, macro recall, and macro F1 score.

In [8]:
import lightgbm as lgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Initialize LGBMClassifier
# Using objective='multiclass' and num_class=10 as there are 10 genome IDs
lgbm_model = lgb.LGBMClassifier(objective='multiclass', num_class=10, random_state=42)

# Train the model
print("Training LightGBM model...")
lgbm_model.fit(X_train, y_train)
print("LightGBM model training complete.")

# Make predictions on the test set
y_pred_lgbm = lgbm_model.predict(X_test)

# Calculate evaluation metrics
accuracy_lgbm = accuracy_score(y_test, y_pred_lgbm)
precision_lgbm = precision_score(y_test, y_pred_lgbm, average='macro', zero_division=0)
recall_lgbm = recall_score(y_test, y_pred_lgbm, average='macro', zero_division=0)
f1_lgbm = f1_score(y_test, y_pred_lgbm, average='macro', zero_division=0)

# Print the results
print(f"\nLightGBM Classifier Performance:")
print(f"Accuracy: {accuracy_lgbm:.4f}")
print(f"Macro Precision: {precision_lgbm:.4f}")
print(f"Macro Recall: {recall_lgbm:.4f}")
print(f"Macro F1-Score: {f1_lgbm:.4f}")

Training LightGBM model...
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.178876 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 979200
[LightGBM] [Info] Number of data points in the train set: 9379, number of used features: 3840
[LightGBM] [Info] Start training from score -3.365485
[LightGBM] [Info] Start training from score -0.486148
[LightGBM] [Info] Start training from score -3.721278
[LightGBM] [Info] Start training from score -3.117950
[LightGBM] [Info] Start training from score -4.016330
[LightGBM] [Info] Start training from score -3.678168
[LightGBM] [Info] Start training from score -2.827260
[LightGBM] [Info] Start training from score -2.179261
[LightGBM] [Info] Start training from score -3.162292
[LightGBM] [Info] Start training from score -3.725693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

KeyboardInterrupt: